# This is a basic workflow to help you get started with Actions

name: Build_Image

env:
  BUILD: 21H2-20240405.0
  S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
  ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  S3_ALIAS: ${{ secrets.S3_ALIAS }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  OUTPUT_PATH: ${{ secrets.OUTPATH }}
  FILE_NAME: win-2k22-datacenter-bios.qcow2


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - win-2k22-datacenter-bios
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Windows]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Building image
        run: |
         ./build_windows_image.ps1 cloud 2k22 datacenter
         echo "Build for Windows Server 2022 Datacenter Cloud image complete"

      - name: Uploading image in object storage
        run: |
         echo "Uploading image in object storage"
         mc alias set ${{ env.S3_ALIAS }} ${{ env.S3_ENDPOINT }} ${{ env.ACCESS_KEY }} ${{ env.SECRET_KEY }}
         mc cp ${{ env.OUTPUT_PATH }}/${{ env.FILE_NAME }} ${{ env.S3_BUCKET }}/latest/${{ env.FILE_NAME }}
         mc cp ${{ env.S3_BUCKET }}/latest/${{ env.FILE_NAME }} ${{ env.S3_BUCKET }}/${{ env.BUILD }}/${{ env.FILE_NAME }}
