# This is a basic workflow to help you get started with Actions

name: Build_Image

env:
  VERSION: 22H1
  BUILD: ${{ github.ref_name }} 
  ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - win-2k22-datacenter-bios
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Windows]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Building image
        run: |
         ./build_windows_image.ps1 cloud 2k22 datacenter
         echo "Build for Windows Server 2022 Datacenter Cloud image complete"

      - name: Uploading image in object storage
        run: |
         echo "Uploading image in object storage"
         mc alias set s3-linit https://s3.linit-infra.net ${{ env.ACCESS_KEY }} ${{ env.SECRET_KEY }}
         mc cp D:\files-output\2k22\win-2k22-datacenter-bios.qcow2 s3-linit/windows-server-2k22-image/${{ env.BUILD }}/win-2k22-datacenter-bios.qcow2
