# This is a basic workflow to help you get started with Actions

name: Build_Image

env:
  VERSION: 22H1
  BUILD: 20230724
  OS_AUTH_URL: ${{ vars.OS_AUTH_URL }}
  ST_AUTH_VERSION: ${{ vars.ST_AUTH_VERSION }}
  OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
  OS_PROJECT_DOMAIN_NAME: ${{ secrets.OS_PROJECT_DOMAIN_NAME }}
  OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
  OS_USERNAME: ${{ secrets.OS_USERNAME }}
  OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - win-2k22-datacenter-uefi
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Windows]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Building image
        run: |
         ./build_windows_image.ps1 cloud 2k22 datacenter
         echo "Build for Windows Server 2022 Datacenter Cloud image complete"

      - name: Uploading image in object storage
        run: |
         swift.exe upload cloud-images D:\files-output\2k22\win-2k22-datacenter-uefi.qcow2 --object-name win2k22/${{ env.BUILD }}/win-2k22-datacenter-uefi.qcow2 --segment-size 5368709120 --use-slo
